<?php
namespace App\Providers;

use App\Exceptions\MyHandler;
use Dingo\Api\Provider\LaravelServiceProvider;

class MyDingoServiceProvider extends LaravelServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
        $this->registerExceptionHandler();
    }
    public function registerExceptionHandler()
    {

        $this->app->singleton('api.exception', function ($app) {
            return new MyHandler($app['Illuminate\Contracts\Debug\ExceptionHandler'], $this->config('errorFormat'), $this->config('debug'));
        });
    }
}